### ISSUE TITLE
Create Install and Run Scripts for Windows

### ISSUE THREAD

**Issue by evanlombardo** [Northeastern-Electric-Racing/Siren#11]
Currently there are scripts for Siren to install Bun and to run it, but no such scripts exist for Windows. Create `install.bat` and `run.bat`, the scripts for Windows users to install and run the Bun application (Siren).

**Comment by evanlombardo** [comment]
https://bun.sh/docs/installation

**Comment by jr1221** [comment]
Siren (websockets) abandoned
