### ISSUE TITLE
Dockerize Siren

### ISSUE THREAD

**Issue by evanlombardo** [Northeastern-Electric-Racing/Siren#12]
Currently we have a Dockerfile that creates a docker image of the siren directory, and we want that image to work with Siren upon build. The Dockerfile should be modified to download the dependencies that Siren needs to run (probably just be the same commands in the install script).

**Comment by nwdepatie** [comment]
Closing as we aren't creating a custom server anymore, but will make a new ticket for a docker development environment for local testing
