### ISSUE TITLE
Integrate timestamp plugin into Mosquitto server

### ISSUE THREAD

**Issue by nwdepatie** [Northeastern-Electric-Racing/Siren#24]
Here is an example plugin of a timestamping functionality:
https://github.com/eclipse/mosquitto/blob/master/plugins/message-timestamp/mosquitto_message_timestamp.c

Here is the corresponding Makefile that is a directory up:
https://github.com/eclipse/mosquitto/blob/master/plugins/message-timestamp/Makefile

Seems relatively easy, probably involves building the whole thing on Linux somehow which kinda sucks but isn't the end of the world

**Comment by jr1221** [comment]
I think Ill change the scope of my PR to encompass complete installation and configuration of mqtt on the odysseus pi.
