### ISSUE TITLE
MQTT Diagnostic Tooling

### ISSUE THREAD

**Issue by nwdepatie** [Northeastern-Electric-Racing/Siren#26]
To debug the server, we need a way of retrieving available MQTT topics and data from the server and visualizing it in a human-readable way. This tool should probably be command line and easy to run.

Tbh there is probably a tool like this already so search for one first, if there isn't one we should make a Python tool to debug the system and visualize. Might be good to have this display throughput, too.

For inspiration, I'm imagining an htop style interface like below
![image](https://github.com/Northeastern-Electric-Racing/Siren/assets/80368116/e88f2420-210b-4dac-884a-3b678074064c)

Note: Pls decouple the backend data retrieval from the frontend visualization service in separate threads

**Comment by jr1221** [comment]
Will implement using https://github.com/EdJoPaTo/mqttui.
