### ISSUE TITLE
Retrieve GPS data

### ISSUE THREAD

**Issue by nwdepatie** [Northeastern-Electric-Racing/Siren#27]
Create a Python script to retrieve GNSS data from our GPS on the custom PCB we are making. This should utilize the Python module foound/made in #25 to publish the GPS data to the MQTT server, too

**Comment by jr1221** [comment]
GPSD client library: https://gpsd.gitlab.io/gpsd/gpsd-client-example-code.html.
It is a sub-optimal implementation that must be read using a while loop,  but could be sent right to mqtt on each loop.

**Comment by jr1221** [comment]
Note we are planning to run on GPSD v3.25.  Use NMEA sentences when fixed.

**Comment by jr1221** [comment]
to be reformated and reopened.

**Comment by jr1221** [comment]
see above

**Comment by jr1221** [comment]
.
