### ISSUE TITLE
Retrieve CPU temperature

### ISSUE THREAD

**Issue by nwdepatie** [Northeastern-Electric-Racing/Siren#28]
The raspberry pi exposes the CPU temperature to the user through a sysfs node, which can be retrieved with the following command:
`cat /sys/class/thermal/thermal_zone0/temp`

We need to integrate this into the general telemetry collection Python script to publish to the MQTT server, similar to #25 and #27

**Comment by jr1221** [comment]
closed, to be reformated and reopened.

**Comment by jr1221** [comment]
.
