### ISSUE TITLE
Publish Messages to Different Topics

### ISSUE THREAD

**Issue by evanlombardo** [Northeastern-Electric-Racing/Siren#4]
Currently all messages are published through the "test" topic, when they should instead have the capability to be sent across any topic. The topic to send will be included in the message JSON.

Sample message:
```
{
   "unix_time": 4362781,
   "topic": "MPU",
   "data": [
      {
         "name": "board_temperature",
         "val": 50,
         "units": "degC"
      },
      {
         "name": "system_state",
         "val": "OFF",
         "units": "enum"
      },
   ...
   ]
}
```
In this case the topic published to should be "MPU".

**Comment by jr1221** [comment]
You mind if I pick this up Evan?  Should be a matter of just using typia on a different structure.

**Comment by evanlombardo** [comment]
> You mind if I pick this up Evan? Should be a matter of just using typia on a different structure.

Sounds good!

**Comment by jr1221** [comment]
Siren (websockets) abandoned
