### ISSUE TITLE
Modify Publisher Python Script

### ISSUE THREAD

**Issue by evanlombardo** [Northeastern-Electric-Racing/Siren#5]
Currently the Python script to test publishing sends a simple string message, but we want it to conform to the message format that we will use to publish to topics. The Python script should be edited to send a sample message to the "test" topic using the following format:
```
{
   "unix_time": 4362781,
   "topic": "MPU",
   "data": [
      {
         "name": "board_temperature",
         "val": 50,
         "units": "degC"
      },
      {
         "name": "system_state",
         "val": "OFF",
         "units": "enum"
      },
   ...
   ]
}
```

**Comment by jr1221** [comment]
Siren (websockets) abandoned
