### ISSUE TITLE
Implement Secure WebSockets

### ISSUE THREAD

**Issue by evanlombardo** [Northeastern-Electric-Racing/Siren#6]
Currently our Python scripts connect to Siren using insecure WebSockets, denoted by the `ws://127.0.0.1:3000` URL that we use. Secure WebSockets would use the URL `wss://127.0.0.1:3000` instead, but Python fails to connect using this secure URL. Investigate and implement the support for secure WebSockets in our server, which uses the Bun framework.

**Comment by jr1221** [comment]
Siren (websockets) abandoned
