### ISSUE TITLE
[Validation] - NanoMQ configuration

### ISSUE THREAD

**Issue by jr1221** [Northeastern-Electric-Racing/Siren#76]
### Description

We need nanomq conf.

### Acceptance Criteria

It needs:

- bridging over quic
- tcp client connections
- sqlite persistence and log rotation (see #68 as alternative and/or supplant)
- no acl
- comments for performance tuning to come later
- plugin loading from `/usr/lib/nanomq/plugin_user_property_timestamp.so`

should be tested over halow link with random data.

### Proposed Solution

Add a conf file in the device tree overlay for the tpu (and nero?).

**Comment by jr1221** [comment]
@evanlombardo any chance you may have some conf files I can work off of?  Ik u had trouble building it so..

**Comment by evanlombardo** [comment]
> @evanlombardo any chance you may have some conf files I can work off of? Ik u had trouble building it so..

yes, check slack in a few minutes
